name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
      - run: pnpm lint

  test:
    name: Test - Node.js v${{matrix.node-version}}
    needs: [lint]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: pnpm test
