name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Node.js v${{matrix.node-version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v3
      - uses: wyvox/action-setup-pnpm@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: pnpm lint
      - run: pnpm test
